export const Restaurants = [
  {
    id: "4709823",
    name: "Baskin Robbins - Ice Cream Desserts",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/4/24/bbc4fee6-b3d6-4d01-98c9-680f8f7779ac_470982.JPG",
    locality: "Eranjal Road",
    areaName: "Chalukunnu",
    costForTwo: "₹250 for two",
    cuisines: ["Desserts", "Ice Cream"],
    avgRating: 2.6,
    veg: true,
    parentId: "5588",
    avgRatingString: "2.6",
    totalRatingsString: "775",
    sla: {
      deliveryTime: 42,
      lastMileTravel: 2.6,
      serviceability: "SERVICEABLE",
      slaString: "40-45 mins",
      lastMileTravelString: "2.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "378010",
    name: "Ibaco",
    cloudinaryImageId: "kawgjvja4kmlhqsfti4o",
    locality: "Kanjikuzhi",
    areaName: "Kottayam",
    costForTwo: "₹300 for two",
    cuisines: ["Ice Cream"],
    avgRating: 4.8,
    veg: true,
    parentId: "3481",
    avgRatingString: "4.8",
    totalRatingsString: "772",
    sla: {
      deliveryTime: 48,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "45-50 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "470982",
    name: "Baskin dfdffd Robbins - Ice Cream Desserts",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/4/24/bbc4fee6-b3d6-4d01-98c9-680f8f7779ac_470982.JPG",
    locality: "Eranjal Road",
    areaName: "Chalukunnu",
    costForTwo: "₹250 for two",
    cuisines: ["Desserts", "Ice Cream"],
    avgRating: 2.6,
    veg: true,
    parentId: "5588",
    avgRatingString: "2.6",
    totalRatingsString: "775",
    sla: {
      deliveryTime: 42,
      lastMileTravel: 2.6,
      serviceability: "SERVICEABLE",
      slaString: "40-45 mins",
      lastMileTravelString: "2.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
];
